import xbmc, xbmcaddon, xbmcgui, xbmcplugin,sys
import os

liste = []	
class sstreamer():
        
    def __init__(self,name ,url):
                self.url=url
               
                self.name=name		
                
		
                self.layoutFinished()
              
    def layoutFinished(self):                                                                     
		
                liste.append((""+self.name, ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))			          
                liste.append(("", ""+self.url))                                  
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))
                liste.append(("", ""+self.url))	                
                self.addLink('[COLOR lightblue][B]OTV MEDIA >>  [/B][/COLOR]' + self.name, self.url) 
 	        
    def addLink(self,name, url):
	        sUrl =(url)
	        sUrl1 =(url)
	        sUrl2 =(url)
	        sUrl3 =(url)
	        sUrl4 =(url)
	        sUrl5 =(url)
	        sUrl6 =(url)
	        sUrl7 =(url)
	     
   
	        playlist=xbmc.PlayList(xbmc.PLAYLIST_VIDEO); 
    
	        playlist.clear();
	        listitem1 = xbmcgui.ListItem(''+name)
	        playlist.add(sUrl,listitem1);
	        listitem2 = xbmcgui.ListItem(''+name)
	        playlist.add(sUrl1,listitem2);
	        listitem3 = xbmcgui.ListItem(''+name)
	        playlist.add(sUrl2,listitem3);
	        listitem4 = xbmcgui.ListItem(''+name)
	        playlist.add(sUrl3,listitem4);
	        listitem5 = xbmcgui.ListItem(''+name)
	        playlist.add(sUrl4,listitem5);                                                                         
	        listitem6 = xbmcgui.ListItem(''+name)
	        playlist.add(sUrl5,listitem6);
	        listitem7 = xbmcgui.ListItem(''+name)
	        playlist.add(sUrl6,listitem7);                                                                         
	        listitem8 = xbmcgui.ListItem(''+name)
	        playlist.add(sUrl7,listitem8);
	        player_type = sPlayerType()
	        xbmcPlayer = xbmc.Player (); 
	        xbmcPlayer.play (playlist)  
	        sys.exit()
	        return ok 
def sPlayerType():
       
        
        try:
            if (sPlayerType == '0'):
               
                return xbmc.PLAYER_CORE_AUTO

            if (sPlayerType == '1'):
                
                return xbmc.PLAYER_CORE_MPLAYER

            if (sPlayerType == '2'):
                
                return xbmc.PLAYER_CORE_DVDPLAYER
        except: return False
          
          
            